project_name: "argocd-vault-plugin"

builds:
  - binary: "argocd-vault-plugin"
    flags: "-trimpath"
    ldflags: >-
      -s -w
      -X "github.com/IBM/argocd-vault-plugin/version.Version={{.Version}}"
      -X "github.com/IBM/argocd-vault-plugin/version.BuildDate={{.Date}}"
      -X "github.com/IBM/argocd-vault-plugin/version.CommitSHA={{.Commit}}"
    mod_timestamp: "{{ $.CommitTimestamp }}"
    env:
      - "CGO_ENABLED=0"
    goarch:
      - amd64
      - arm
      - arm64
    tags:
      - netgo
      - static_build

release:
  prerelease: "false"

changelog:
  filters:
    exclude:
      - "^(refactor|style|test|docs|ci)(\\([^)]+\\))?(!)?:"
